services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dev-db}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpassword}
    volumes:
      - mysql:/var/lib/mysql

  db-ui:
    image: adminer
    depends_on:
      - mysql
    ports:
      - ${ADMINER_PORT:-8888}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=dracula

volumes:
  mysql:
